### PR TITLE
Pause message over the screen

### PR DESCRIPTION
**Pull request by jainamritanshu**
Hi @cristobalmedinalopez @josmanual 
I have added a pause message over screen which stays as long as the video is paused and disappears as soon as the video is played by himself/other peer
I have taken all the edge cases into account such as no toasts in DOM present/same peer pause/plays the video and more
This should work fine in reference to #14 :smile:

### CODE REVIEW

**Comment by jainamritanshu** [comment]
@cristobalmedinalopez @josmanual I have also added the feature to start/stop webcam as well as audio properly in the last [commit](https://github.com/P2PSP/Virtual-Room/pull/21/commits/3194ecf9f11a00c8f65c1f650fb8dd3937a10cc8) in reference to #20 
I am still trying to reproduce the previous problem of append buffer :smile:

**Comment by cristobalmedinalopez** [comment]
Hi @jainamritanshu 
Would be possible to use an avatar default image instead of a black screen when "Stop Webcam" is pressed?

**Comment by jainamritanshu** [comment]
Sure @cristobalmedinalopez
I will do the needful asap and update the PR 😁

**Comment by jainamritanshu** [comment]
Hi @cristobalmedinalopez 
I have updated the PR to replace black screen with default avatar at stop webcam :smile:

**Comment by cristobalmedinalopez** [comment]
Thanks!

**Pull request merged**
