### PR TITLE
fixed hardcoded URLs in reference to issue #6

### PR DESCRIPTION
**Pull request by jainamritanshu**
I have fixed the hardcoded URLs in the `room.js`. Introduced a new variable domainURL. Hope it seems fine now :smile:

### CODE REVIEW

**Comment by jainamritanshu** [comment]
Hi, I have used 
`window.location.host` and `window.location.port` to determine the whole domainURL, hope this works fine! :smile:

**Comment by josmangarsal** [comment]
Thanks! Now it's much better but the signaling server url should be also dynamic. You can use `hostURL` to create `signalServer` in `room.js`.

**Comment by jainamritanshu** [comment]
Sure @josmanual I am on it. Just a question, I guess I would have to at least hardcode the signal server port in the file?

**Comment by josmangarsal** [comment]
Yes I think so, use a global var to define it.

**Comment by cristobalmedinalopez** [comment]
@jainamritanshu Yes, we will use the port hardcoded (for now ;-))

**Comment by cristobalmedinalopez** [comment]
BTW, I added a new option to test script. You can give the port number as a parameter for the built-in web server. Commit: https://github.com/P2PSP/Virtual-Room/commit/bdad61847fdd46828124ba5cbf19af695c035d71

**Comment by jainamritanshu** [comment]
I have replaced the hardcoded URL for signal server as well. Please have a look
Also should we define another separate variable for signal server URL, since developers might not prefer to use the same servers for client and server side?

**Comment by josmangarsal** [comment]
For now we can use the same url for both, at least for testing I think.

**Pull request merged**
